#!/bin/bash
#
# pinp - plays local files and streaming video in a picture-in-picture window
#
# This script requires mpv and youtube-dl
#


# Config file 
PINPCONF="$HOME/.config/pinp/pinp.conf"

# Create config file if does not exist
if [ ! -f $PINPCONF ]; then
       install -D -m644 /etc/pinp/pinp.conf.default $PINPCONF 
fi

# Import settings from config file
#. $PINPCONF
. /home/james/LOCAL/github/pinp/pinp.conf.default

# Set basic options to enable mpv picture-in-picture mode
mpv_options="--ontop --no-border --on-all-workspaces --autofit=$SIZE --geometry=$POSITION"

# Make format more flexible for google video search
if [[ "$SEARCH" -eq "gvsearch" ]]; then
        FORMAT="[height<=?720]"
fi


play_local()
{
        mpv $mpv_options "$1"
}

stream_url()
{
        mpv $mpv_options --ytdl-format $FORMAT "$1" 
}

stream_search()
{
    mpv $mpv_options $(youtube-dl --format $FORMAT --get-url "$SEARCH$NUMBER:$1") 
}

date_search()
{

        case "$1" in

                day) DATE="now-1day";;

                week) DATE="now-1week";;

                month) DATE="now-1month";;

        esac

        mpv $mpv_options $(youtube-dl --format $FORMAT --dateafter $DATE --get-url "$SEARCH$NUMBER:$2") 

}

# Set number of videos to stream if specified
if [[ "$2" =~ ^[0-9]*$ ]]; then
        NUMBER=$2
elif [[ "$3" =~ ^[0-9]*$ ]]; then
        NUMBER=$3
fi


if [[ "$1" =~ ^"http" ]]; then
        stream_url "$1"
elif [[ -f "$1" ]]; then
        play_local "$1"
else
        case "$1" in

                hq) FORMAT="$BEST_FORMAT"
                    stream_url "$2";;

                gvs) SEARCH="gvsearch"
                    stream_search "$2";;

                day|week|month) date_search "$1" "$2";;

                *) stream_search "$1";;
        esac

fi

