#!/bin/bash
#
# ytjb - plays audio from youtube 
#
# This script requires mpv and youtube-dl
#

# Config file 
PINPCONF="$HOME/.config/pinp/pinp.conf"

# Create config file if does not exist
if [ ! -f $PINPCONF ]; then
       install -D -m644 /etc/pinp/pinp.conf.default $PINPCONF 
fi

# Import settings from config file
#. $PINPCONF
. /home/james/LOCAL/github/pinp/pinp.conf.default



stream_songs()
{
    mpv "$1" --no-video
}

stream_search()
{
    mpv $(youtube-dl --format bestaudio --get-url "$SEARCH$A_NO:$1") 
}


# Set number of clips to stream if specified
if [[ -n "$2" && "$2" =~ ^[0-9]*$ ]]; then
                A_NO=$2
elif [[ -n "$3" && "$3" =~ ^[0-9]*$ ]]; then
                A_NO=$3
fi



if [[ "$1" =~ ^"http" ]]; then
        stream_songs "$1"
else
        case "$1" in

                sc) SEARCH="scsearch"
                    stream_search "$2";;
                
                *) stream_search "$1";;

        esac

fi 
